#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Nelson Ponzoni Resume
url: 'https://lerker.github.io/'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Nelson Ponzoni Resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: green # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: G-96F4450391

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
