version: "2"
services:
  jekyll:
      image: jekyll/jekyll:3.9
      command: bundle exec jekyll serve --force_polling
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
      environment:
        JEKYLL_UID: 1001
        JEKYLL_GID: 1001
