name: Link Check

on:
  push:
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --path vendor/bundle
      - name: Build site
        run: bundle exec jekyll build
        - name: Check links
          run: bundle exec htmlproofer ./_site --url-ignore https://themes.3rdwavemedia.com
